"""First recommedation table creation

Revision ID: a9691b1147ed
Revises: 
Create Date: 2024-04-01 13:58:48.269741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9691b1147ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposal_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bucket', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('gVision_labels', sa.String(length=255), nullable=True),
    sa.Column('gtp_selected_label', sa.String(length=64), nullable=True),
    sa.Column('label_correction', sa.String(length=64), nullable=True),
    sa.Column('disposal_guidance', sa.String(length=255), nullable=True),
    sa.Column('disposal_guidance_correction', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disposal_recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disposal_recommendation_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disposal_recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disposal_recommendation_timestamp'))

    op.drop_table('disposal_recommendation')
    # ### end Alembic commands ###
