"""raised maximum field length for recommendation

Revision ID: b1d05ec28eb7
Revises: fbbbd987c458
Create Date: 2024-04-02 10:12:18.447914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d05ec28eb7'
down_revision = 'fbbbd987c458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disposal_recommendation', schema=None) as batch_op:
        batch_op.alter_column('disposal_guidance',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disposal_recommendation', schema=None) as batch_op:
        batch_op.alter_column('disposal_guidance',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
