"""upated field name

Revision ID: fbbbd987c458
Revises: a9691b1147ed
Create Date: 2024-04-01 15:14:48.035685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbbd987c458'
down_revision = 'a9691b1147ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disposal_recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_uri', sa.String(length=64), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disposal_recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('file_uri')

    # ### end Alembic commands ###
